# GitHub Sponsors and custom funding links
# Add your PayPal hosted donation link to show a "Sponsor" button on the repo

# github: your-username   # Uncomment and set if you have GitHub Sponsors
custom:
  - https://www.paypal.com/donate/?hosted_button_id=VKSXG8EFYYXDC
