using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Media;
using ModbusForge.Helpers;
using ModbusForge.Services;

namespace ModbusForge
{
    public partial class KeyboardShortcutsWindow : Window
    {
        private readonly IDialogService _dialogService;

        public KeyboardShortcutsWindow(IDialogService? dialogService = null)
        {
            InitializeComponent();
            _dialogService = dialogService ?? new NullDialogService();
        }

        private void Close_Click(object sender, RoutedEventArgs e)
        {
            Close();
        }

        private void Print_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                var printDialog = new PrintDialog();
                if (printDialog.ShowDialog() == true)
                {
                    var printDocument = new FlowDocument();
                    printDocument.FontFamily = new FontFamily("Segoe UI");
                    printDocument.FontSize = 12;
                    printDocument.PagePadding = new Thickness(48);
                    printDocument.PageWidth = printDialog.PrintableAreaWidth;
                    printDocument.PageHeight = printDialog.PrintableAreaHeight;
                    printDocument.ColumnWidth = printDialog.PrintableAreaWidth;

                    // Title
                    printDocument.Blocks.Add(new Paragraph(new Run("ModbusForge Keyboard Shortcuts"))
                    {
                        FontSize = 18,
                        FontWeight = FontWeights.Bold,
                        Margin = new Thickness(0, 0, 0, 16)
                    });

                    AddShortcutSection(printDocument, "Global Shortcuts", new[]
                    {
                        ("Ctrl + R", "Read registers"),
                        ("Ctrl + T", "Open trends"),
                        ("Ctrl + S", "Save project"),
                        ("Ctrl + O", "Open project"),
                        ("Ctrl + N", "New project"),
                        ("F5", "Refresh data"),
                        ("F1", "Open help")
                    });

                    AddShortcutSection(printDocument, "Script Editor", new[]
                    {
                        ("Ctrl + N", "New script"),
                        ("Ctrl + O", "Open script"),
                        ("Ctrl + S", "Save script"),
                        ("Ctrl + E", "Execute script")
                    });

                    AddShortcutSection(printDocument, "Visual Node Editor", new[]
                    {
                        ("Ctrl + Z", "Undo last action"),
                        ("Ctrl + Y", "Redo"),
                        ("Ctrl + Shift + Z", "Redo (alternate)"),
                        ("Delete", "Delete selected node"),
                        ("Esc", "Cancel operation / clear search"),
                        ("Right-click wire", "Delete connection"),
                        ("Scroll Wheel", "Scroll vertically"),
                        ("Shift + Scroll", "Scroll horizontally"),
                        ("Ctrl + Scroll", "Zoom in/out"),
                        ("Middle Drag", "Pan canvas")
                    });

                    printDocument.Blocks.Add(new Paragraph(new Run("Generated by ModbusForge"))
                    {
                        FontSize = 9,
                        Foreground = BrushCache.GetBrush(Colors.Gray),
                        Margin = new Thickness(0, 16, 0, 0)
                    });

                    printDialog.PrintDocument(((IDocumentPaginatorSource)printDocument).DocumentPaginator, "ModbusForge Keyboard Shortcuts");
                }
            }
            catch (System.Exception ex)
            {
                _dialogService.Show($"Failed to print: {ex.Message}", "Print Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private static void AddShortcutSection(FlowDocument document, string title, (string shortcut, string description)[] shortcuts)
        {
            document.Blocks.Add(new Paragraph(new Run(title))
            {
                FontSize = 14,
                FontWeight = FontWeights.SemiBold,
                Margin = new Thickness(0, 12, 0, 6)
            });

            var table = new Table();
            table.Columns.Add(new TableColumn { Width = new GridLength(150) });
            table.Columns.Add(new TableColumn { Width = new GridLength(1, GridUnitType.Star) });

            var rowGroup = new TableRowGroup();
            foreach (var (shortcut, description) in shortcuts)
            {
                var row = new TableRow();
                var shortcutCell = new TableCell(new Paragraph(new Run(shortcut)) { FontWeight = FontWeights.SemiBold });
                var descCell = new TableCell(new Paragraph(new Run(description)));
                row.Cells.Add(shortcutCell);
                row.Cells.Add(descCell);
                rowGroup.Rows.Add(row);
            }
            table.RowGroups.Add(rowGroup);
            document.Blocks.Add(table);
        }
    }
}
