name: Build Installer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish Application
      run: dotnet publish .\ModbusForge\ModbusForge.csproj -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -p:PublishTrimmed=false -o .\publish\win-x64

    - name: Setup Inno Setup
      uses: jr-g/setup-inno-setup-action@v1

    - name: Compile Installer
      run: iscc.exe "setup\ModbusForge.iss"

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ModbusForge-Installer
        path: installers\*.exe
