name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    timeout-minutes: 45

    steps:
    - name: Checkout repository
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Setup .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test --configuration Release --no-build --verbosity normal --filter 'FullyQualifiedName!~UITests & FullyQualifiedName!~SmokeTests'
